services:
  nextjs-standalone:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-standalone-image
    container_name: nextjs-standalone-container
    environment:
      NODE_ENV: production
      PORT: "3000"
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    env_file: ".env"
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data: