version: "0.2"
ignorePaths: [".dockerignore","Dockerfile","compose.yml", ".example.env"]
dictionaryDefinitions: []
dictionaries: []
words:
  - autoincrement
  - cuid
  - treeify
ignoreWords: []
import: []
